name: sonar_scraper
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  web_scraper: ^0.1.4
  webdriver: ^3.1.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
